puppycompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField , TextAreaField , SubmitField
from wtforms.validators import DataRequired

class BlogPostsForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Submit')

puppycompanyblog/blog_posts/views.py
from flask import render_template, url_for, redirect, flash , request , Blueprint
from puppycompanyblog import db
from puppycompanyblog.blog_posts.forms import BlogPostsForm
from puppycompanyblog.models import BlogPosts,User
from flask_login import login_required, current_user

blog_posts = Blueprint('blog_posts', __name__)


#Create a new blog post
@blog_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    
    form = BlogPostsForm()
    
    if form.validate_on_submit():
        blog_post = BlogPosts(title= form.title.data,
                             content= form.content.data,
                             author_id= current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash('Blog post created')
        return redirect(url_for('core.index'))
    
    return render_template('create_post.html', form=form)
    



#View all blog posts

@blog_posts.route('/<int:blog_post_id>')
def blog_post_view(blog_post_id):
    blogpost  = BlogPosts.query.get_or_404(blog_post_id)
    return render_template('blog_post.html' , blogpost=blogpost)




#Update blog posts
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(blog_post_id):
    blogpost = BlogPosts.query.get_or_404(blog_post_id)

    if blogpost.author_id != current_user.id :
        abort(403)
        
    form = BlogPostsForm()
    
    if form.validate_on_submit():
        blogpost.title = form.title.data
        blogpost.content = form.content.data
        db.session.commit()
        flash('Blog post updated')
        return redirect(url_for('blogposts.blog_post_view', blog_post_id=blog_post_id))
    elif request.method == 'GET':
        form.title.data = blogpost.title
        form.content.data = blogpost.content
        
    return render_template('create_post.html' , title='Update Post' , form=form)



#Delete blog post

@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blogpost = BlogPosts.query.get_or_404(blog_post_id)
    if blogpost.author_id != current_user.id :
        abort(403)
    
    db.session.delete(blogpost)
    db.session.commit()
    flash('Blog post deleted')
    return redirect(url_for('core.index'))

puppycompanyblog/core/views.py
from flask import render_template,redirect,Blueprint , request
from puppycompanyblog.models import BlogPosts

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1 , type=int)
    posts = BlogPosts.query.order_by(BlogPosts.date_posted.desc()).paginate(page=page , per_page=2)
    return render_template('index.html' , posts=posts)

@core.route('/about')
def about():
    return render_template('about.html')

puppycompanyblog/users/views.py
from flask import  render_template , redirect, request , flash , url_for , Blueprint
from flask_login import login_required , current_user , login_user , logout_user
from puppycompanyblog import db
from puppycompanyblog.users.forms import LoginForm, RegistrationForm , UpdateUserForm
from puppycompanyblog.users.picture_handler import add_profile_pic
from puppycompanyblog.models import User , BlogPosts
 
users = Blueprint('users',__name__)

#register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User( email= form.email.data,
                    username= form.username.data,
                    password= form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in','success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

#login
@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if  user is not None and user.check_password(form.password.data):
            login_user(user)
            flash('You are Logged in successfully')
            
            next = request.args.get('next')
            
            if next == None or not next[0] == '/' :
                next = url_for('core.index')
            
            return redirect(next)
    return render_template('login.html' , form=form)


#logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

#account
@users.route('/account',  methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    
    if form.validate_on_submit():
        if form.picture.data :
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            print(pic)
            current_user.profile_image = pic
         
        current_user.username = form.username.data   
        current_user.email = form.email.data
        current_user.password = form.password.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        
        
    profile_pic = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', form = form , profile_pic = profile_pic)    


@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPosts.query.filter_by(author=user).order_by(BlogPosts.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html' , blog_posts= blog_posts , user=user)

puppycompanyblog/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h4> About Our Company</h4>
    <p> Welcome </p>
{% endblock %}

puppycompanyblog/templates/account.html
{% extends 'base.html' %} {% block content %}

<div class="h-100 d-flex align-items-center justify-content-center">
  <div class="container mt-5 center">
    <!-- Profile Image -->
    <div class="text-center">
      <h2>Welcome to {{current_user.username}}'s profile page</h2>
      <br />
    </div>
    <img
      src="{{url_for('static', filename='profile_pics/' + current_user.profile_image)}}"
      class="rounded-circle mx-auto d-block"
      alt=" {{current_user.username}}'s Profile Picture"
      width="200"
    />
    <br />
  </div>
</div>
<form method="POST" action="" enctype="multipart/form-data">
  <div class="form-group">
    {{form.hidden_tag()}} {{form.email.label}}{{form.email(class="form-control"
    , id="exampleInputEmail1" )}}
  </div>

  <div class="form-group">
    {{form.username.label}}{{form.username(class="form-control" )}}
  </div>

  <div class="form-group">
    {{form.password.label}}{{form.password(class="form-control" ,
    id="exampleInputPassword1" )}}
  </div>

  <div class="form-group">
    {{form.picture.label}}{{form.picture(class="form-control-file" ,
    id="exampleFormControlFile1" )}}
  </div>

  {{form.submit(class="btn btn-primary")}}
</form>

{% endblock %}

puppycompanyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <ul class="nav justify-content">
      <li class="nav-item">
        <a class="nav-link active" href="{{url_for('core.index')}}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('core.about')}}">About Us</a>
      </li>

      {% if current_user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('blog_posts.create')}}"
          >Create Post</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('users.logout')}}">Log out</a>
      </li>

      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('users.login')}}">Log in</a>
      </li>

      {% endif %}
    </ul>
    <div class="jumbotron jumbotron-fluid">
      <div class="container">{% block content %} {% endblock %}</div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

puppycompanyblog/templates/blog_post.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <h4>{{post.title}}</h4>
  <h5>Written by: {{post.author.username}}</h5>
  <h6>Published at: {{post.date_posted.strftime(%B %d, %Y)}}</h6>

  <p>{{post.content}}</p>

  {% if post.author == current_user %}
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <a
          href="{{url_for('blogposts.update_post', id=post.id)}}"
          class="btn btn-primary"
          >Edit Post</a
        >
      </div>
      <div class="col-md-6">
        <button
          type="button"
          class="btn btn-danger"
          data-toggle="modal"
          data-target="#del-modal"
        >
          Delete Post
        </button>
      </div>
    </div>
  </div>

  <!-- Button trigger modal -->
  <!-- Modal -->
  <div
    class="modal fade"
    id="del-modal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Post?</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure to you want delete this post ?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>

          <form method="post" action="{{url_for('blogposts.delete_post' , blog_post_id = post.id)}}">
            <input type="submit" class="btn btn-danger">Delete</button>
          </form>
          <a
            href="{{url_for('blogposts.delete_post', id=post.id)}}"
            class="btn btn-danger"
            >Delete Post</a
          >
        </div>
      </div>
    </div>
  </div>

  {% endif %}
</div>

{% endblock %}

puppycompanyblog/templates/create_post.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <form method="post">
    <div class="form-group">
      {{form.hidden_tag()}}
      {{form.title.label}}{{form.title(class="form-control" )}}
    </div>

    <div class="form-group">
      {{form.content.label}}{{form.content(class="form-control" )}}
    </div>

    {{form.submit(class="btn btn-primary")}}
  </form>
</div>

{% endblock %}

puppycompanyblog/templates/index.html
{% extends 'base.html' %} {% block content %}
<h4>Welocme to Puppy Company Website</h4>

{% for post in posts.items %}
<div class="container">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">{{post.title}}</h5>

      <h6 style="display: inline">
        Written by :
        <a
          href="{{url_for('users.user_posts' , username=post.author.username)}}"
          class="card-link"
        >
          {{post.author.username}}
        </a>
      </h6>
      <!-- Add a little space -->
      <span style="margin-right: 10px"></span>
      <h6 class="card-subtitle mb-2 text-muted" style="display: inline">
        Published at : {{post.date_posted.strftime('%Y-%m-%d')}}
      </h6>

      <br />
      <p class="card-text">{{post.content[0:231]}}</p>

      <a
        href="{{url_for('core.index') , blog_post_id = post.id }}"
        class="card-link"
        >Read more</a
      >
    </div>
  </div>
</div>
<br />
{% endfor %}

<nav aria-label="Page Navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
    left_current=1,right_current=2) %} {% if posts.page == page_num %}
    <li class="page-item disabled">
      <a class="page-link" href="{{url_for('core.index',   page = page_num)}}"
        >{{ page_num }}</a
      >
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="{{url_for('core.index',  page = page_num)}}"
        >{{ page_num }}</a
      >
    </li>
    {% endif %} {% endfor %}
  </ul>
</nav>
{% endblock %}

puppycompanyblog/templates/login.html
{% extends 'base.html' %} {% block content %}
<form method="POST">
  <div class="form-group">
    {{form.hidden_tag()}} {{form.email.label}}{{form.email(class="form-control"
    , id="exampleInputEmail1")}}
  </div>

  <div class="form-group">
    {{form.password.label}}{{form.password(class="form-control" ,
    id="exampleInputPassword1" )}}
  </div>

  {{form.submit(class="btn btn-primary")}}
</form>
{% endblock %}

puppycompanyblog/templates/register.html
{% extends 'base.html' %} {% block content %}
<form method="POST">
  <div class="form-group">
    {{form.hidden_tag()}} {{form.email.label}}{{form.email(class="form-control"
    , id="exampleInputEmail1" )}}
  </div>
  <div class="form-group">
    {{form.username.label}}{{form.username(class="form-control" ,
    id="exampleInputEmail1" )}}
  </div>
  <div class="form-group">
    {{form.password.label}}{{form.password(class="form-control" ,
    id="exampleInputPassword1" )}}
  </div>
  <div class="form-group">
    {{form.pass_confirm.label}}{{form.pass_confirm(class="form-control" ,
    id="exampleInputPassword1" )}}
  </div>

  {{form.submit(class="btn btn-primary")}}
</form>
{% endblock %}

puppycompanyblog/templates/user_blog_posts.html
{% extends 'base.html' %} {% block content %}
<div class="h-100 d-flex align-items-center justify-content-center">
  <div class="container mt-5 center">
    <!-- Profile Image -->
    <div class="text-center">
      <h2>Welcome to {{current_user.username}}'s profile page</h2>
      <br />
    </div>
    <img
      src="{{url_for('static', filename='profile_pics/' + current_user.profile_image)}}"
      class="rounded-circle mx-auto d-block"
      alt=" {{current_user.username}}'s Profile Picture"
      width="200"
    />
    <br />
  </div>
</div>
<div>
  {% for post in blog_posts.items %}
  <div class="container">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>

        <h6 style="display: inline">
          Written by :
          <a
            href="{{url_for('users.user_posts' , username=post.author.username)}}"
            class="card-link"
          >
            {{post.author.username}}
          </a>
        </h6>
        <!-- Add a little space -->
        <span style="margin-right: 10px"></span>
        <h6 class="card-subtitle mb-2 text-muted" style="display: inline">
          Published at : {{post.date_posted.strftime('%Y-%m-%d')}}
        </h6>

        <br />
        <p class="card-text">{{post.content[0:231]}}</p>

        <a
          href="{{url_for('core.index' , blog_post_id = post.id) }}"
          class="card-link"
          >Read more</a
        >
      </div>
    </div>
  </div>
  <br />
  {% endfor %}
</div>

<nav aria-label="Page Navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1,
    left_current=1,right_current=2) %} {% if blog_posts.page == page_num %}
    <li class="page-item disabled">
      <a
        class="page-link"
        href="{{url_for('users.user_posts', username = user.username , page = page_num)}}"
        >{{page_num}}</a
      >
    </li>
    {% else %}
    <li class="page-item">
      <a
        class="page-link"
        href="{{url_for('users.user_posts', username = user.username , page = page_num)}}"
        >{{page_num}}</a
      >
    </li>
    {% endif %} {% endfor %}
  </ul>
</nav>

{% endblock %}